ORS_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjIyOTg0ZmU2ZDhmNjQ5ODFiOTg4YmUyZWMyMmQxOTdjIiwiaCI6Im11cm11cjY0In0="

SUPABASE_URL = "https://aoneyjidmcrzaoratguk.supabase.co"
SUPABASE_KEY = "sb_publishable_wx4dgrZtS8cRyYB8kpoWzQ_Hi7ykJHt"

GOOGLE_KEY = "AIzaSyD0aTE_GCj4g5aw0Kjan3MeIK1DPJ0vubA"